### ISSUE TITLE
Component test fails using signals for state management

### ISSUE THREAD

**Issue by cdoremus** [uki00a/fresh-testing-library#20]
I tried to write a `fresh-testing-library` test for a component in an app that uses signals for state management and the test fails. 

The test code can be found here (with the component-under-test and other code in the same branch):
https://github.com/cdoremus/fresh-todo-signals/blob/fresh-testing-lib/tests/AddTodo_test.tsx

This is a full error trace:
```
craig@craig-G750JX:~/git/deno/blog/deno-blog-apps/fresh-todo-signals$ deno task test
Task test deno test -A
running 1 test from ./tests/AddTodo_test.tsx
AddTodo.tsx test ...
  should add todo... ... FAILED (13ms)
AddTodo.tsx test ... FAILED (due to 1 failed step) (86ms)

 ERRORS 

AddTodo.tsx test ... should add todo... => https://deno.land/std@0.193.0/testing/_test_suite.ts:323:15
error: TypeError: Cannot read properties of undefined (reading 'value')
          value={currentTodo.value}
                             ^
    at T.AddTodo [as constructor] (file:///home/craig/git/deno/blog/deno-blog-apps/fresh-todo-signals/islands/AddTodo.tsx:16:30)
    at T.ce [as render] (https://esm.sh/stable/preact@10.15.1/denonext/preact.mjs:2:8524)
    at O (https://esm.sh/stable/preact@10.15.1/denonext/preact.mjs:2:6232)
...
```

**Comment by cdoremus** [comment]
I was able to fix the tests. I was not using the Preact context in my tests that the components were using.
