### ISSUE TITLE
TypeError found when testing the Carousel component from the Fresh repo

### ISSUE THREAD

**Issue by cdoremus** [uki00a/fresh-testing-library#22]
I am trying to write `fresh-testing-library` tests for the [Fresh components](https://fresh.deno.dev/components) section of the Fresh web site using the source code in the Fresh repo. I have a test for the Carousel component that fails with a `TypeError` and the message: "G1.Image is not a constructor" (see below). 

The test's stack trace does not help me debug this issue. I suspect that the problem has something to do with a third-party library used by the component (`tabler_icons_tsx`). I understand that you cannot be expected to fix the library, but a more precise stack-trace would be nice.

The source code for my tests and (with the associated component-under-test) is found here:
https://github.com/cdoremus/fresh/blob/fresh-testing-lib/tests/components/gallery/Carousel.test.tsx

Test run with stack-trace:
```
craig@craig-G750JX:~/git/deno/denoland/fresh/fresh_fork$ deno test -A tests/components/gallery/Carousel.test.tsx
Check file:///home/craig/git/deno/denoland/fresh/fresh_fork/tests/components/gallery/Carousel.test.tsx
running 1 test from ./tests/components/gallery/Carousel.test.tsx
Carousel.tsx ...
  should display navigation buttons ...
------- output -------
[UNKNOWN_DIRECTIVE] {"rule":"slide"}
----- output end -----
  should display navigation buttons ... FAILED (50ms)
Carousel.tsx ... FAILED (due to 1 failed step) (127ms)

 ERRORS 

Carousel.tsx ... should display navigation buttons => https://deno.land/std@0.193.0/testing/_test_suite.ts:323:15
error: TypeError: G1.Image is not a constructor
    at yN._updateTheImageData (https://esm.sh/v126/jsdom@22.1.0/denonext/jsdom.mjs:793:288493)
    at yN._attrModified (https://esm.sh/v126/jsdom@22.1.0/denonext/jsdom.mjs:793:287567)
    at Object.Et.changeAttribute (https://esm.sh/v126/jsdom@22.1.0/denonext/jsdom.mjs:12:56577)
    at yN.setAttribute (https://esm.sh/v126/jsdom@22.1.0/denonext/jsdom.mjs:792:114667)
    at HTMLImageElement.setAttribute (https://esm.sh/v126/jsdom@22.1.0/denonext/jsdom.mjs:792:122919)
    at M (https://esm.sh/stable/preact@10.15.1/denonext/preact.mjs:2:4453)
    at se (https://esm.sh/stable/preact@10.15.1/denonext/preact.mjs:2:3542)
    at ue (https://esm.sh/stable/preact@10.15.1/denonext/preact.mjs:2:7658)
    at O (https://esm.sh/stable/preact@10.15.1/denonext/preact.mjs:2:6668)
    at X (https://esm.sh/stable/preact@10.15.1/denonext/preact.mjs:2:2148)

 FAILURES 

Carousel.tsx ... should display navigation buttons => https://deno.land/std@0.193.0/testing/_test_suite.ts:323:15

FAILED | 0 passed | 1 failed (1 step) (1s)
```

**Comment by uki00a** [comment]
Thanks for the report! In conclusion, this error seems to be caused by [node-canvas](https://github.com/Automattic/node-canvas) not loading properly :cry:

---

This error appears to occur in the following line:
- https://github.com/jsdom/jsdom/blob/22.1.0/lib/jsdom/living/nodes/HTMLImageElement-impl.js#L82

The `Canvas` referenced here is initialized with the following code:

- https://github.com/jsdom/jsdom/blob/22.1.0/lib/jsdom/utils.js#L149

I tried specifying the `?deps` option when importing `jsdom`, but this did not work:

```typescript
export { JSDOM } from "https://esm.sh/jsdom@22.1.0?no-dts&deps=canvas@2.11.2&pin=v132";
```
I tried to import `node-canvas` directly from `esm.sh` as a test:

```typescript
import * as nodeCanvas from "https://esm.sh/canvas@2.11.2?no-dts&pin=v132";
console.info(nodeCanvas);
```

It seems that `node-canvas` is not initialized properly:

```
[Module: null prototype] {
  Canvas: undefined,
  CanvasGradient: undefined,
  CanvasPattern: undefined,
  CanvasRenderingContext2D: undefined,
  Context2d: undefined,
  DOMMatrix: undefined,
  DOMPoint: undefined,
  Image: undefined,
  ImageData: undefined,
  JPEGStream: undefined,
  PDFStream: undefined,
  PNGStream: undefined,
  backends: undefined,
  cairoVersion: undefined,
  createCanvas: [Function (anonymous)],
  createImageData: [Function (anonymous)],
  default: {
    parseFont: [Function (anonymous)],
    createCanvas: [Function (anonymous)],
    createImageData: [Function (anonymous)],
    loadImage: [Function (anonymous)]
  },
  deregisterAllFonts: undefined,
  freetypeVersion: undefined,
  gifVersion: undefined,
  jpegVersion: undefined,
  loadImage: [Function (anonymous)],
  pangoVersion: undefined,
  parseFont: [Function (anonymous)],
  registerFont: undefined,
  rsvgVersion: undefined,
  version: undefined
}
```
